const rules = {
  "accessor-pairs": "error",
  "block-scoped-var": "error",
  complexity: "warn",
  "consistent-return": "error",
  "default-case": "error",
  eqeqeq: ["error", "allow-null"],
  "guard-for-in": "error",
  "no-alert": "warn",
  "no-caller": "error",
  "no-div-regex": "error",
  "no-else-return": "error",
  "no-labels": "error",
  "no-eq-null": "off",
  "no-eval": "error",
  "no-extend-native": "error",
  "no-extra-bind": "error",
  "no-fallthrough": "error",
  "no-implicit-coercion": [
    "error",
    { string: true, number: true, boolean: true },
  ],
  "no-iterator": "error",
  "no-lone-blocks": "error",
  "no-multi-str": "error",
  "no-native-reassign": "error",
  "no-new-func": "error",
  "no-new-wrappers": "error",
  "no-new": "error",
  "no-octal-escape": "error",
  "no-octal": "error",
  "no-param-reassign": "off",
  "no-process-env": "off",
  "no-proto": "error",
  "no-return-assign": "error",
  "no-script-url": "error",
  "no-self-compare": "error",
  "no-sequences": "error",
  "no-useless-call": "error",
  "no-useless-concat": "error",
  "no-void": "error",
  "no-warning-comments": [
    "warn",
    { terms: ["todo", "fixme"], location: "anywhere" },
  ],
  "no-with": "error",
  radix: "error",
  yoda: ["error", "never"],
};

export default { rules };
