const rules = {
  "accessor-pairs": "error",
  "block-scoped-var": "error",
  complexity: ["warn", { max: 15 }],
  "consistent-return": "error",
  "default-case": "error",
  "default-case-last": "error",
  eqeqeq: ["error", "allow-null"],
  "guard-for-in": "error",
  "no-alert": "warn",
  "no-caller": "error",
  "no-div-regex": "error",
  "no-else-return": ["error", { allowElseIf: false }],
  "no-empty-function": "error",
  "no-empty-pattern": "error",
  "no-eq-null": "off",
  "no-eval": "error",
  "no-extend-native": "error",
  "no-extra-bind": "error",
  "no-extra-label": "error",
  "no-fallthrough": "error",
  "no-implicit-coercion": [
    "error",
    { string: true, number: true, boolean: true },
  ],
  "no-implicit-globals": "error",
  "no-implied-eval": "error",
  "no-iterator": "error",
  "no-labels": "error",
  "no-lone-blocks": "error",
  "no-loop-func": "error",
  "no-multi-str": "error",
  "no-new-func": "error",
  "no-new-wrappers": "error",
  "no-new": "error",
  "no-octal-escape": "error",
  "no-octal": "error",
  "no-param-reassign": ["error", { props: false }],
  "no-proto": "error",
  "no-return-assign": "error",
  "no-return-await": "error",
  "no-script-url": "error",
  "no-self-assign": "error",
  "no-self-compare": "error",
  "no-sequences": "error",
  "no-throw-literal": "error",
  "no-unmodified-loop-condition": "error",
  "no-unused-expressions": [
    "error",
    { allowShortCircuit: true, allowTernary: true },
  ],
  "no-useless-call": "error",
  "no-useless-concat": "error",
  "no-useless-return": "error",
  "no-void": "error",
  "no-warning-comments": [
    "warn",
    { terms: ["todo", "fixme"], location: "anywhere" },
  ],
  "no-with": "error",
  "prefer-promise-reject-errors": "error",
  "prefer-regex-literals": "error",
  radix: "error",
  "require-await": "error",
  yoda: ["error", "never"],
};

export default { rules };
