const rules = {
  "for-direction": "error",
  "getter-return": "error",
  "no-async-promise-executor": "error",
  "no-cond-assign": ["error", "always"],
  "no-console": "warn",
  "no-constant-condition": "error",
  "no-control-regex": "error",
  "no-debugger": "warn",
  "no-dupe-args": "error",
  "no-dupe-else-if": "error",
  "no-dupe-keys": "error",
  "no-duplicate-case": "error",
  "no-empty-character-class": "error",
  "no-empty": "error",
  "no-ex-assign": "error",
  "no-extra-boolean-cast": "error",
  "no-func-assign": "error",
  "no-import-assign": "error",
  "no-inner-declarations": ["error", "both"],
  "no-invalid-regexp": "error",
  "no-irregular-whitespace": "error",
  "no-misleading-character-class": "error",
  "no-obj-calls": "error",
  "no-promise-executor-return": "error",
  "no-prototype-builtins": "error",
  "no-regex-spaces": "error",
  "no-setter-return": "error",
  "no-sparse-arrays": "error",
  "no-template-curly-in-string": "error",
  "no-unreachable": "error",
  "no-unreachable-loop": "error",
  "no-unsafe-finally": "error",
  "no-unsafe-negation": ["error", { enforceForOrderingRelations: true }],
  "no-useless-backreference": "error",
  "require-atomic-updates": "error",
  "use-isnan": "error",
  "valid-typeof": ["error", { requireStringLiterals: true }],
};

export default { rules };
