const rules = {
  "no-cond-assign": ["error", "always"],
  "no-console": "warn",
  "no-constant-condition": "error",
  "no-control-regex": "error",
  "no-debugger": "warn",
  "no-dupe-args": "error",
  "no-dupe-keys": "error",
  "no-duplicate-case": "error",
  "no-empty-character-class": "error",
  "no-empty": "error",
  "no-ex-assign": "error",
  "no-extra-boolean-cast": "error",
  "no-func-assign": "error",
  "no-inner-declarations": ["error", "both"],
  "no-invalid-regexp": "error",
  "no-irregular-whitespace": "error",
  "no-negated-in-lhs": "error",
  "no-obj-calls": "error",
  "no-regex-spaces": "error",
  "no-sparse-arrays": "error",
  "no-unreachable": "error",
  "use-isnan": "error",
  "valid-typeof": "error",
};

export default { rules };
