language: node_js
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    rooms:
      - secure: PT817SWqu3u5rPesZEbESWmLtiaREhjQZ5Y3eTmO03Kizz1ublAF0nJUWxPbItgybpKDJUpwPV62RyI2YjUQDhOB2B43X77Z4RLej7JLJ+hrHof+S7AmEGop0plGK4mKK4OGw80V8fPvi+ZJaZnvoqXkDsk/QuhcbcX51sGXMm/PGn0IJ366sYOphl7u7Og5f/XBPEJMCo3QshBnaQMEp+mmvXNJSujprOkHFG5lqRWV14uf5jOolcLKYq6MYBi4g/f8nYeox/ts1e9wOiXy7QMKCKQTzM/TRn8sB5XbE6lSea8zOkIRVcixQWfo3OC2uxWsXW/Q2IceTGtwtkjtsTYQ1SQN5hBHIEepbBsy6kroh9/z+t4OwICV6q+SdPJ6ULfcuMoFD8VtQLXm2cNCb2iR80t18WwC2t65f4ijVEAgxDWXHPu1zm4fOcN2wUwnHxj75aVMIdCOgCDQCU20ofLvDX46v3zwtlCWywR70Vchi9B4V0VY8p0TigIUmQte7PrfUdZTT+z8bo35FlkNd/H8d5BoMBNlivtqkfAK7qIYef790KQZbsqIDGUvGULiWwzUIre1uXYJhsGvKxdm0eeIXLcfWcWHuOsxQQwwChefArTM5utNAD+VNRLNOGtEx1NC90Vvl4IFWSNhYaKz9byg/fVstL+KhJ8a1exuXYQ=
