name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Detail the bad behavior and the steps required to duplicate it
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
      description: What did you expect to happen when performing the action?
      placeholder: Expected behavior
      value: "Expected behavior"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of this library are you running?
      placeholder: "v0.0.0"
      value: 
    validations:
      required: true
  - type: textarea
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      description: |
        List browsers where you see the problem reported. For example:
          * Mac OS 15.3.5, Chrome 130.0.1234.987
          * Android 14, Firefox 133.0
          * iPadOS 17.1, Safari
      placeholder: 'For each browser specify 1) operating system and version 2) browser name and version'

